{% set name = "anaconda-auth" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anaconda/anaconda-auth/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6e952baf3ca2276b660187895b620274428f22a6576edd734ac490e22bb88279

build:
  entry_points:
    - conda-token = anaconda_auth._conda.conda_token:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >={{ python_min }}
    - keyring
    - pkce
    - python-dotenv
    - pydantic
    - pyjwt
    - requests
    - cryptography >=3.4.0
    - semver <4
    - anaconda-cli-base >=0.7.0
  run_constrained:
    - conda >=23.9.0
    - conda-token >=0.7.0
    - anaconda-cloud-auth >=0.8

test:
  imports:
    - anaconda_auth
  commands:
    - conda-token --help
    - anaconda auth --help
    - python -c "from anaconda_auth import __version__; assert __version__ == \"{{ version }}\""
  requires:
    - python {{ python_min }}
    - conda

about:
  summary: A client auth library for Anaconda APIs
  doc_url: https://anaconda.github.io/anaconda-auth
  dev_url: https://github.com/anaconda/anaconda-auth
  home: https://anaconda.com
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlbertDeFusco
    - mattkram
